#!/bin/bash
GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;35m"
NC="\033[0m" # No Color

run_command() {
    INPUT="$1"
    echo -e "${YELLOW}Input: ${NC}"
    echo -e "$INPUT"

    # Capture the command output
    OUTPUT=$(./minishell "$INPUT" 2>&1)
    EXIT=$(echo $? 2>&1)
    ACTUAL=$(bash -c "$INPUT" 2>&1)
    EXIT_ACTUAL=$(echo $? 2>&1)

echo -e "${YELLOW}Output: ${NC}"
    echo -e "$OUTPUT"
    echo -e "${YELLOW}Actual: ${NC}"
    echo -e "$ACTUAL"

    # Run valgrind and capture its output
    valgrind -q --leak-check=full --error-exitcode=222 ./minishell "$INPUT" &>/dev/null
    if [ $? -eq 222 ]; then
        echo -e "${YELLOW}Valgrind: ${RED}KO${NC}"
    else
        echo -e "${YELLOW}Valgrind: ${GREEN}OK${NC}"
    fi

    if [ $EXIT -eq $EXIT_ACTUAL ]; then
        echo -e "${YELLOW}Compare: ${NC} $EXIT_ACTUAL  ${GREEN}OK${NC}"
    else
        echo -e "${YELLOW}Compare: ${NC} $EXIT_ACTUAL  ${RED}NOT SAME${NC}"
    fi

    echo -e "${GREEN}--------------------------------------------------------------------${NC}"
}

    run_command "echo"
    run_command "echo -n"
    run_command "echo -n hi"
    run_command "echo -n      \"Hi\""
    run_command "echo   -n   \"Hello \$USER\" ', nice day;)'"
    run_command "echo 'Hi \$\$'"
    run_command "echo '[Hello \"World\"]'"
    run_command "   echo  \"[Hello 'World'']\""
    run_command "echo \"Hello \$USER lol \" -n \"\$SHELL\""
    run_command "echo hello        world ls echo"
    run_command "echo \"Hello               world ls\" go"
    run_command "echo -nnnn Hello World"
    run_command "echo -n -n -nnnn -nnnnm"
    run_command "echo hi\";\" hihi"
    run_command "echo \"Hello\"     \"World\""
    run_command "echo \"Hello\"\"World\""
    run_command "echo \"Hello      World\""
    run_command "echo is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    run_command "echo \"EE"
    run_command "export X='i lolo' && ech\$X"
    run_command "export X='i -n lolo' && ech\$X"
    run_command "export X='o -n lolo' && ech\$X"
    run_command "export X='o -n lolo' && ech\"\$X\""
    run_command "echo echo"
    run_command "exit"
    run_command "echo -n hi && exit"
    run_command "rwer || exit"
    run_command "rwer && exit"
    run_command "exit -n"
    run_command "exit ./"
    run_command "exit 0"
    run_command "exit 1"
    run_command "exit 125"
    run_command "exit +1"
    run_command "exit -12456"
    run_command "exit test last"
    run_command "exit x 1"
    run_command "exit 0 hello"
    run_command "exit 55 70"
    run_command "exit exit"
    run_command "cd"
    run_command "unset HOME && cd"
    run_command "cd ."
    run_command "cd ."
    run_command "cd \"../../\""
    run_command "cd /"
    run_command "cd directory"
    run_command "cd ./subdir"
    run_command "cd /home"
    run_command "cd /usr/bin"
    run_command "cd /usr/bin ./home"
    run_command "cd ~"
    run_command "cd -"
    run_command "cd invalid_path"
    run_command "cd cd"
    run_command "pwd"
    run_command "pwd a b c d"
    run_command "pwd pwd"
    run_command "env"
    run_command "env env"
    run_command "env a b c"
    run_command "env env env"
    run_command "export"
    run_command "export TEST=test"
    run_command "export TEST='[check]'"
    run_command "export TEST=\"['TEST']\""
    run_command "export TEST=\"['test' \$SHELL]\""
    run_command "export VAR=\"Hello\""
    run_command "export VAR=yoyo TEST=dada"
    run_command "export TEST=test user"
    run_command "export \"test=ici\"=coucou"
    run_command "export _A55=Rolling+"
    run_command "export word="
    run_command "export TEST"
    run_command "export \"\" NEW=t unset \"\""
    run_command "export =Yoyo"
    run_command "export \$DD"
    run_command "export VAR = \"Hello\""
    run_command "export #sddfs"
    run_command "export 312=313"
    run_command "export export 55@=Time"
    run_command "export variable-name"
    run_command "export float*=test"
    run_command "export \"float*\"=ok"
    run_command "unset"
    run_command "unset VAR=Hello"
    run_command "unset VAR"
    run_command "unset HELLO="
    run_command "unset VAR TEST"
    run_command "unset unset"
    run_command "(export SHELL= && env | grep SHELL=)"
    run_command "unset 3413423 ewqeeq"
    run_command "unset PWD && (env | grep PWD=) && cd ../ &&  (env | grep PWD=) "
    # run_command "clear fdskondsfkl fsdnkl;fds"
    # run_command "clear 13231"
    # run_command "clear clear"